-- Still Writer 최초 PostgreSQL 스키마
-- 대상: Supabase PostgreSQL
-- 주의: 실제 DB에 적용하기 전에 대상 프로젝트와 백업 여부를 다시 확인합니다.

BEGIN;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(191) NOT NULL,
    password_hash VARCHAR(255),
    nickname VARCHAR(50) NOT NULL,
    profile_image_url VARCHAR(2048),
    email_verified_at TIMESTAMPTZ(6),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    last_login_at TIMESTAMPTZ(6),
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    withdrawn_at TIMESTAMPTZ(6),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_nickname UNIQUE (nickname),
    CONSTRAINT ck_users_email_normalized CHECK (email = lower(email)),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN')),
    CONSTRAINT ck_users_withdrawn_state CHECK (
        (status = 'WITHDRAWN' AND withdrawn_at IS NOT NULL)
        OR (status <> 'WITHDRAWN' AND withdrawn_at IS NULL)
    )
);

CREATE TABLE auth_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(20) NOT NULL,
    provider_user_id VARCHAR(191) NOT NULL,
    provider_email VARCHAR(191),
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_auth_identities_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_auth_identities_provider_user UNIQUE (provider, provider_user_id),
    CONSTRAINT uq_auth_identities_user_provider UNIQUE (user_id, provider),
    CONSTRAINT ck_auth_identities_provider CHECK (provider IN ('LOCAL', 'GOOGLE', 'KAKAO'))
);

CREATE TABLE user_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    refresh_token_hash CHAR(64) NOT NULL,
    device_name VARCHAR(100),
    ip_address INET,
    user_agent VARCHAR(500),
    expires_at TIMESTAMPTZ(6) NOT NULL,
    revoked_at TIMESTAMPTZ(6),
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_sessions_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_user_sessions_refresh_token_hash UNIQUE (refresh_token_hash),
    CONSTRAINT ck_user_sessions_expiry CHECK (expires_at > created_at),
    CONSTRAINT ck_user_sessions_revoked_at CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash CHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ(6) NOT NULL,
    used_at TIMESTAMPTZ(6),
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_password_reset_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT ck_password_reset_tokens_expiry CHECK (expires_at > created_at),
    CONSTRAINT ck_password_reset_tokens_used_at CHECK (used_at IS NULL OR used_at >= created_at)
);

CREATE TABLE user_settings (
    user_id BIGINT PRIMARY KEY,
    theme VARCHAR(10) NOT NULL DEFAULT 'SYSTEM',
    font_family VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    font_size SMALLINT NOT NULL DEFAULT 16,
    line_height NUMERIC(3, 1) NOT NULL DEFAULT 1.6,
    paragraph_gap VARCHAR(10) NOT NULL DEFAULT 'NORMAL',
    auto_indent BOOLEAN NOT NULL DEFAULT TRUE,
    char_count_mode VARCHAR(20) NOT NULL DEFAULT 'INCLUDE_SPACES',
    export_format VARCHAR(10) NOT NULL DEFAULT 'TXT',
    locale VARCHAR(10) NOT NULL DEFAULT 'ko-KR',
    timezone VARCHAR(50) NOT NULL DEFAULT 'Asia/Seoul',
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_settings_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_user_settings_theme CHECK (theme IN ('SYSTEM', 'LIGHT', 'DARK')),
    CONSTRAINT ck_user_settings_font_size CHECK (font_size BETWEEN 8 AND 72),
    CONSTRAINT ck_user_settings_line_height CHECK (line_height BETWEEN 1.0 AND 3.0),
    CONSTRAINT ck_user_settings_paragraph_gap CHECK (paragraph_gap IN ('NARROW', 'NORMAL', 'WIDE')),
    CONSTRAINT ck_user_settings_char_count_mode CHECK (
        char_count_mode IN ('INCLUDE_SPACES', 'EXCLUDE_SPACES')
    ),
    CONSTRAINT ck_user_settings_export_format CHECK (
        export_format IN ('TXT', 'DOCX', 'PDF', 'MARKDOWN')
    )
);

CREATE TABLE external_storage_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    provider_account_id VARCHAR(191) NOT NULL,
    account_email VARCHAR(191),
    access_token_encrypted BYTEA,
    refresh_token_encrypted BYTEA,
    token_expires_at TIMESTAMPTZ(6),
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    disconnected_at TIMESTAMPTZ(6),
    CONSTRAINT fk_external_storage_accounts_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_external_storage_accounts_identity
        UNIQUE (user_id, provider, provider_account_id),
    CONSTRAINT ck_external_storage_accounts_provider CHECK (provider IN ('GOOGLE_DRIVE')),
    CONSTRAINT ck_external_storage_accounts_disconnected_at CHECK (
        disconnected_at IS NULL OR disconnected_at >= created_at
    )
);

CREATE TABLE folders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    parent_id BIGINT,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    category VARCHAR(10) NOT NULL DEFAULT 'GENERAL',
    color CHAR(7),
    target_char_count INTEGER,
    diary_auto_date BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    last_used_at TIMESTAMPTZ(6),
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ(6),
    purge_after TIMESTAMPTZ(6),
    CONSTRAINT fk_folders_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_folders_parent FOREIGN KEY (parent_id)
        REFERENCES folders (id) ON DELETE SET NULL,
    CONSTRAINT ck_folders_category CHECK (category IN ('NOVEL', 'DIARY', 'MEMO', 'GENERAL')),
    CONSTRAINT ck_folders_color CHECK (color IS NULL OR color ~ '^#[0-9A-Fa-f]{6}$'),
    CONSTRAINT ck_folders_target_char_count CHECK (
        target_char_count IS NULL OR target_char_count >= 0
    ),
    CONSTRAINT ck_folders_novel_target CHECK (
        category = 'NOVEL' OR target_char_count IS NULL
    ),
    CONSTRAINT ck_folders_soft_delete CHECK (
        (deleted_at IS NULL AND purge_after IS NULL)
        OR (deleted_at IS NOT NULL AND purge_after IS NOT NULL AND purge_after >= deleted_at)
    )
);

CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    folder_id BIGINT,
    type VARCHAR(10) NOT NULL DEFAULT 'GENERAL',
    title VARCHAR(50) NOT NULL DEFAULT '',
    content_json JSONB NOT NULL,
    plain_text TEXT NOT NULL,
    char_count INTEGER NOT NULL DEFAULT 0,
    char_count_without_spaces INTEGER NOT NULL DEFAULT 0,
    word_count INTEGER NOT NULL DEFAULT 0,
    sentence_count INTEGER NOT NULL DEFAULT 0,
    target_char_count INTEGER,
    diary_date DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    revision BIGINT NOT NULL DEFAULT 0,
    completed_at TIMESTAMPTZ(6),
    last_opened_at TIMESTAMPTZ(6),
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ(6),
    purge_after TIMESTAMPTZ(6),
    CONSTRAINT fk_documents_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_documents_folder FOREIGN KEY (folder_id)
        REFERENCES folders (id) ON DELETE SET NULL,
    CONSTRAINT ck_documents_type CHECK (type IN ('NOVEL', 'DIARY', 'MEMO', 'GENERAL')),
    CONSTRAINT ck_documents_status CHECK (status IN ('DRAFT', 'IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT ck_documents_counts CHECK (
        char_count >= 0
        AND char_count_without_spaces >= 0
        AND word_count >= 0
        AND sentence_count >= 0
        AND revision >= 0
    ),
    CONSTRAINT ck_documents_target_char_count CHECK (
        target_char_count IS NULL OR target_char_count >= 0
    ),
    CONSTRAINT ck_documents_novel_target CHECK (type = 'NOVEL' OR target_char_count IS NULL),
    CONSTRAINT ck_documents_diary_date CHECK (type = 'DIARY' OR diary_date IS NULL),
    CONSTRAINT ck_documents_completed_at CHECK (
        (status = 'COMPLETED' AND completed_at IS NOT NULL)
        OR (status <> 'COMPLETED' AND completed_at IS NULL)
    ),
    CONSTRAINT ck_documents_soft_delete CHECK (
        (deleted_at IS NULL AND purge_after IS NULL)
        OR (deleted_at IS NOT NULL AND purge_after IS NOT NULL AND purge_after >= deleted_at)
    )
);

CREATE TABLE document_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    version_no INTEGER NOT NULL,
    save_request_id UUID NOT NULL,
    title VARCHAR(50) NOT NULL DEFAULT '',
    content_json JSONB NOT NULL,
    plain_text TEXT NOT NULL,
    char_count INTEGER NOT NULL DEFAULT 0,
    version_type VARCHAR(10) NOT NULL DEFAULT 'AUTO',
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_document_versions_document FOREIGN KEY (document_id)
        REFERENCES documents (id) ON DELETE CASCADE,
    CONSTRAINT uq_document_versions_number UNIQUE (document_id, version_no),
    CONSTRAINT uq_document_versions_request UNIQUE (document_id, save_request_id),
    CONSTRAINT ck_document_versions_number CHECK (version_no >= 1),
    CONSTRAINT ck_document_versions_char_count CHECK (char_count >= 0),
    CONSTRAINT ck_document_versions_type CHECK (version_type IN ('AUTO', 'RESTORE'))
);

CREATE TABLE favorites (
    user_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_favorites PRIMARY KEY (user_id, document_id),
    CONSTRAINT fk_favorites_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_favorites_document FOREIGN KEY (document_id)
        REFERENCES documents (id) ON DELETE CASCADE
);

CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    color CHAR(7),
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tags_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_tags_user_name UNIQUE (user_id, name),
    CONSTRAINT ck_tags_color CHECK (color IS NULL OR color ~ '^#[0-9A-Fa-f]{6}$')
);

CREATE TABLE document_tags (
    document_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_document_tags PRIMARY KEY (document_id, tag_id),
    CONSTRAINT fk_document_tags_document FOREIGN KEY (document_id)
        REFERENCES documents (id) ON DELETE CASCADE,
    CONSTRAINT fk_document_tags_tag FOREIGN KEY (tag_id)
        REFERENCES tags (id) ON DELETE CASCADE
);

CREATE TABLE materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    source_document_id BIGINT,
    type VARCHAR(10) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    content_snapshot JSONB,
    original_file_name VARCHAR(255),
    storage_provider VARCHAR(30),
    storage_key VARCHAR(1024),
    mime_type VARCHAR(191),
    file_size BIGINT,
    checksum_sha256 CHAR(64),
    metadata JSONB,
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ(6),
    purge_after TIMESTAMPTZ(6),
    CONSTRAINT fk_materials_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_materials_source_document FOREIGN KEY (source_document_id)
        REFERENCES documents (id) ON DELETE SET NULL,
    CONSTRAINT ck_materials_type CHECK (type IN ('DOCUMENT', 'FILE', 'IMAGE')),
    CONSTRAINT ck_materials_storage_provider CHECK (
        storage_provider IS NULL OR storage_provider IN ('APP_STORAGE', 'GOOGLE_DRIVE', 'S3')
    ),
    CONSTRAINT ck_materials_file_size CHECK (file_size IS NULL OR file_size >= 0),
    CONSTRAINT ck_materials_checksum CHECK (
        checksum_sha256 IS NULL OR checksum_sha256 ~ '^[0-9A-Fa-f]{64}$'
    ),
    CONSTRAINT ck_materials_document_source CHECK (
        type = 'DOCUMENT' OR source_document_id IS NULL
    ),
    CONSTRAINT ck_materials_soft_delete CHECK (
        (deleted_at IS NULL AND purge_after IS NULL)
        OR (deleted_at IS NOT NULL AND purge_after IS NOT NULL AND purge_after >= deleted_at)
    )
);

CREATE TABLE material_tags (
    material_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_material_tags PRIMARY KEY (material_id, tag_id),
    CONSTRAINT fk_material_tags_material FOREIGN KEY (material_id)
        REFERENCES materials (id) ON DELETE CASCADE,
    CONSTRAINT fk_material_tags_tag FOREIGN KEY (tag_id)
        REFERENCES tags (id) ON DELETE CASCADE
);

CREATE TABLE document_materials (
    document_id BIGINT NOT NULL,
    material_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_document_materials PRIMARY KEY (document_id, material_id),
    CONSTRAINT fk_document_materials_document FOREIGN KEY (document_id)
        REFERENCES documents (id) ON DELETE CASCADE,
    CONSTRAINT fk_document_materials_material FOREIGN KEY (material_id)
        REFERENCES materials (id) ON DELETE CASCADE
);

CREATE TABLE document_shares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL,
    share_token_hash CHAR(64) NOT NULL,
    permission VARCHAR(10) NOT NULL DEFAULT 'READ',
    expires_at TIMESTAMPTZ(6),
    revoked_at TIMESTAMPTZ(6),
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_document_shares_document FOREIGN KEY (document_id)
        REFERENCES documents (id) ON DELETE CASCADE,
    CONSTRAINT fk_document_shares_creator FOREIGN KEY (created_by)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_document_shares_token_hash UNIQUE (share_token_hash),
    CONSTRAINT ck_document_shares_permission CHECK (permission IN ('READ')),
    CONSTRAINT ck_document_shares_expiry CHECK (expires_at IS NULL OR expires_at > created_at),
    CONSTRAINT ck_document_shares_revoked_at CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE TABLE daily_writing_stats (
    stat_date DATE NOT NULL,
    user_id BIGINT NOT NULL,
    chars_written INTEGER NOT NULL DEFAULT 0,
    documents_created INTEGER NOT NULL DEFAULT 0,
    documents_updated INTEGER NOT NULL DEFAULT 0,
    writing_seconds INTEGER NOT NULL DEFAULT 0,
    goal_char_count INTEGER,
    goal_achieved BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_daily_writing_stats PRIMARY KEY (stat_date, user_id),
    CONSTRAINT fk_daily_writing_stats_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_daily_writing_stats_counts CHECK (
        chars_written >= 0
        AND documents_created >= 0
        AND documents_updated >= 0
        AND writing_seconds >= 0
        AND (goal_char_count IS NULL OR goal_char_count >= 0)
    )
);

-- 인증 및 만료 데이터 조회
CREATE INDEX idx_user_sessions_user_expires
    ON user_sessions (user_id, expires_at);
CREATE INDEX idx_password_reset_tokens_user_expires
    ON password_reset_tokens (user_id, expires_at);

-- 삭제되지 않은 사용자 데이터의 주요 목록 조회
CREATE INDEX idx_folders_active_recent
    ON folders (user_id, last_used_at DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_folders_active_hierarchy
    ON folders (user_id, parent_id, sort_order)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_documents_active_recent
    ON documents (user_id, updated_at DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_documents_active_folder_recent
    ON documents (user_id, folder_id, updated_at DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_documents_active_type_recent
    ON documents (user_id, type, updated_at DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_documents_active_diary_date
    ON documents (user_id, diary_date)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_favorites_user_created
    ON favorites (user_id, created_at DESC);
CREATE INDEX idx_materials_active_recent
    ON materials (user_id, created_at DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_materials_active_type
    ON materials (user_id, type)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_materials_source_document
    ON materials (source_document_id);

-- 영구 삭제 배치 대상 조회
CREATE INDEX idx_folders_purge_after
    ON folders (purge_after)
    WHERE purge_after IS NOT NULL;
CREATE INDEX idx_documents_purge_after
    ON documents (purge_after)
    WHERE purge_after IS NOT NULL;
CREATE INDEX idx_materials_purge_after
    ON materials (purge_after)
    WHERE purge_after IS NOT NULL;

-- 공유와 통계 조회
CREATE INDEX idx_document_shares_document_revoked
    ON document_shares (document_id, revoked_at);
CREATE INDEX idx_daily_writing_stats_user_date
    ON daily_writing_stats (user_id, stat_date DESC);

-- Spring Boot가 JDBC로만 접근하므로 Supabase Data API 역할에는 권한을 부여하지 않습니다.
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated, service_role;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
    REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
    REVOKE USAGE, SELECT ON SEQUENCES FROM anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
    REVOKE EXECUTE ON FUNCTIONS FROM anon, authenticated, service_role;

COMMIT;
