-- Still Writer 문서-외부 파일 연결 테이블 추가
-- 대상: Supabase PostgreSQL
-- 목적: Google Drive 내보내기, 문서 단위 백업, 동기화 대상 파일을 문서와 연결해 관리합니다.

BEGIN;

CREATE TABLE document_external_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    external_storage_account_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    provider_file_id VARCHAR(512) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    mime_type VARCHAR(191),
    export_format VARCHAR(10) NOT NULL,
    purpose VARCHAR(20) NOT NULL DEFAULT 'EXPORT',
    sync_status VARCHAR(20) NOT NULL DEFAULT 'LINKED',
    web_view_link VARCHAR(2048),
    remote_revision_id VARCHAR(191),
    remote_modified_at TIMESTAMPTZ(6),
    last_synced_at TIMESTAMPTZ(6),
    last_exported_at TIMESTAMPTZ(6),
    last_imported_at TIMESTAMPTZ(6),
    last_error_message VARCHAR(1000),
    checksum_sha256 CHAR(64),
    metadata JSONB,
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_document_external_files_document FOREIGN KEY (document_id)
        REFERENCES documents (id) ON DELETE CASCADE,
    CONSTRAINT fk_document_external_files_storage_account FOREIGN KEY (external_storage_account_id)
        REFERENCES external_storage_accounts (id) ON DELETE CASCADE,
    CONSTRAINT uq_document_external_files_remote
        UNIQUE (external_storage_account_id, provider_file_id),
    CONSTRAINT uq_document_external_files_document_format
        UNIQUE (document_id, external_storage_account_id, purpose, export_format),
    CONSTRAINT ck_document_external_files_provider CHECK (provider IN ('GOOGLE_DRIVE')),
    CONSTRAINT ck_document_external_files_export_format CHECK (
        export_format IN ('TXT', 'DOCX', 'PDF', 'MARKDOWN')
    ),
    CONSTRAINT ck_document_external_files_purpose CHECK (
        purpose IN ('EXPORT', 'BACKUP', 'SYNC')
    ),
    CONSTRAINT ck_document_external_files_sync_status CHECK (
        sync_status IN ('LINKED', 'SYNCED', 'PENDING', 'FAILED', 'CONFLICT', 'DISCONNECTED')
    ),
    CONSTRAINT ck_document_external_files_checksum CHECK (
        checksum_sha256 IS NULL OR checksum_sha256 ~ '^[0-9A-Fa-f]{64}$'
    ),
    CONSTRAINT ck_document_external_files_sync_time CHECK (
        last_synced_at IS NULL
        OR last_exported_at IS NULL
        OR last_synced_at >= last_exported_at
    )
);

CREATE INDEX idx_document_external_files_document
    ON document_external_files (document_id, purpose, updated_at DESC);

CREATE INDEX idx_document_external_files_account_status
    ON document_external_files (external_storage_account_id, sync_status, updated_at DESC);

CREATE INDEX idx_document_external_files_pending
    ON document_external_files (sync_status, updated_at)
    WHERE sync_status IN ('PENDING', 'FAILED', 'CONFLICT');

-- Spring Boot JDBC만 DB에 직접 접근하므로 Supabase Data API 역할에는 권한을 부여하지 않습니다.
REVOKE ALL ON TABLE document_external_files FROM anon, authenticated, service_role;
REVOKE ALL ON SEQUENCE document_external_files_id_seq FROM anon, authenticated, service_role;

COMMIT;
