-- Still Writer 이메일 인증 코드 테이블 추가
-- 대상: Supabase PostgreSQL
-- 목적: 회원가입 이메일 인증 코드를 해시로 저장하고 만료/검증 상태를 관리합니다.

BEGIN;

CREATE TABLE email_verification_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(191) NOT NULL,
    purpose VARCHAR(20) NOT NULL DEFAULT 'SIGNUP',
    code_hash CHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ(6) NOT NULL,
    verified_at TIMESTAMPTZ(6),
    consumed_at TIMESTAMPTZ(6),
    attempt_count SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_email_verification_codes_email_normalized CHECK (email = lower(email)),
    CONSTRAINT ck_email_verification_codes_purpose CHECK (purpose IN ('SIGNUP')),
    CONSTRAINT ck_email_verification_codes_expiry CHECK (expires_at > created_at),
    CONSTRAINT ck_email_verification_codes_verified_at CHECK (
        verified_at IS NULL OR verified_at >= created_at
    ),
    CONSTRAINT ck_email_verification_codes_consumed_at CHECK (
        consumed_at IS NULL OR consumed_at >= created_at
    ),
    CONSTRAINT ck_email_verification_codes_attempt_count CHECK (
        attempt_count >= 0 AND attempt_count <= 10
    )
);

CREATE INDEX idx_email_verification_codes_email_purpose_recent
    ON email_verification_codes (email, purpose, created_at DESC);

CREATE INDEX idx_email_verification_codes_valid
    ON email_verification_codes (email, purpose, code_hash, expires_at)
    WHERE verified_at IS NULL AND consumed_at IS NULL;

CREATE INDEX idx_email_verification_codes_expires
    ON email_verification_codes (expires_at)
    WHERE verified_at IS NULL AND consumed_at IS NULL;

-- Spring Boot JDBC만 DB에 직접 접근하므로 Supabase Data API 역할에는 권한을 부여하지 않습니다.
REVOKE ALL ON TABLE email_verification_codes FROM anon, authenticated, service_role;
REVOKE ALL ON SEQUENCE email_verification_codes_id_seq FROM anon, authenticated, service_role;

COMMIT;
