BEGIN;

CREATE TABLE IF NOT EXISTS oauth_exchange_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_hash CHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    provider VARCHAR(20) NOT NULL,
    expires_at TIMESTAMPTZ(6) NOT NULL,
    consumed_at TIMESTAMPTZ(6),
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_oauth_exchange_codes_code_hash UNIQUE (code_hash),
    CONSTRAINT fk_oauth_exchange_codes_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_oauth_exchange_codes_provider
        CHECK (provider IN ('GOOGLE', 'KAKAO')),
    CONSTRAINT ck_oauth_exchange_codes_expires_at
        CHECK (expires_at > created_at),
    CONSTRAINT ck_oauth_exchange_codes_consumed_at
        CHECK (consumed_at IS NULL OR consumed_at >= created_at)
);

CREATE INDEX IF NOT EXISTS idx_oauth_exchange_codes_expires
    ON oauth_exchange_codes (expires_at)
    WHERE consumed_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_user_sessions_active_user
    ON user_sessions (user_id, expires_at)
    WHERE revoked_at IS NULL;

COMMIT;
